name: Build and Test Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.1

      - name: build
        run: go build -o dooms.bin main.go

      - name: test
        run: go test ./... -v --race
